version: '3'
# Persistent volume for the db and build 
#volumes:
#  db-data:
#    driver: local
#    driver_opts:
#      type: none
#      device: ${DB_VOLUME}
#      o: bind
#  build-volume:
#    driver: local
#    driver_opts:
#      type: none
#      device: ${BUILD_VOLUME}
#      o: bind
volumes:
  build-volume:
services:
  darkstar-db:
    container_name: darkstar-db
    build: 
      context: darkstar-db
      FFXI_REPO: ${FFXI_REPO}
      FFXI_BRANCH: ${FFXI_BRANCH}
    ports:
     - "23055:3306"
    volumes:
     - ${DB_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_LOGIN}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZONE_IP: ${ZONE_IP}
  darkstar-dsbuild:
    container_name: darkstar-dsbuild
    build:
      context: darkstar-dsbuild
      args:
        FFXI_REPO: ${FFXI_REPO}
        FFXI_BRANCH: ${FFXI_BRANCH}
        VER_LOCK: ${VER_LOCK}
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZONE_IP: ${ZONE_IP}
      SERVERNAME: ${SERVERNAME}
      skillup_chance_multiplier: ${skillup_chance_multiplier}
      craft_chance_multiplier: ${craft_chance_multiplier}
      player_hp_multiplier: ${player_hp_multiplier}
      player_mp_multiplier: ${player_mp_multiplier}
      max_merit_points: ${max_merit_points}
      ENABLE_COP: ${ENABLE_COP}
      ENABLE_TOAU: ${ENABLE_TOAU}
      ENABLE_WOTG: ${ENABLE_WOTG}
      ENABLE_ACP: ${ENABLE_ACP}
      ENABLE_AMK: ${ENABLE_AMK}
      ENABLE_ASA: ${ENABLE_ASA}
      ENABLE_ABYSSEA: ${ENABLE_ABYSSEA}
      ENABLE_SOA: ${ENABLE_SOA}
      ENABLE_ROV: ${ENABLE_ROV}
      ENABLE_VOIDWATCH: ${ENABLE_VOIDWATCH}
      INITIAL_LEVEL_CAP: ${INITIAL_LEVEL_CAP}
      MAX_LEVEL: ${MAX_LEVEL}
      NORMAL_MOB_MAX_LEVEL_RANGE_MIN: ${NORMAL_MOB_MAX_LEVEL_RANGE_MIN}
      NORMAL_MOB_MAX_LEVEL_RANGE_MAX: ${NORMAL_MOB_MAX_LEVEL_RANGE_MAX}
      START_GIL: ${START_GIL}
      START_INVENTORY: ${START_INVENTORY}
      OPENING_CUTSCENE_ENABLE: ${OPENING_CUTSCENE_ENABLE}
      ALL_MAPS: ${ALL_MAPS}
      UNLOCK_OUTPOST_WARPS: ${UNLOCK_OUTPOST_WARPS}
      USE_ADOULIN_WEAPON_SKILL_CHANGES: ${USE_ADOULIN_WEAPON_SKILL_CHANGES}
      HEALING_TP_CHANGE: ${HEALING_TP_CHANGE}
      LandKingSystem_NQ: ${LandKingSystem_NQ}
      LandKingSystem_HQ: ${LandKingSystem_HQ}
      BETWEEN_2DYNA_WAIT_TIME: ${BETWEEN_2DYNA_WAIT_TIME}
      DYNA_MIDNIGHT_RESET: ${DYNA_MIDNIGHT_RESET}
      DYNA_LEVEL_MIN: ${DYNA_LEVEL_MIN}
      TIMELESS_HOURGLASS_COST: ${TIMELESS_HOURGLASS_COST}
      PRISMATIC_HOURGLASS_COST: ${PRISMATIC_HOURGLASS_COST}
      CURRENCY_EXCHANGE_RATE: ${CURRENCY_EXCHANGE_RATE}
      RELIC_2ND_UPGRADE_WAIT_TIME: ${RELIC_2ND_UPGRADE_WAIT_TIME}
      RELIC_3RD_UPGRADE_WAIT_TIME: ${RELIC_3RD_UPGRADE_WAIT_TIME}
      FREE_COP_DYNAMIS: ${FREE_COP_DYNAMIS}
      OldSchoolG1: ${OldSchoolG1}
      OldSchoolG2: ${OldSchoolG2}
      FrigiciteDuration: ${FrigiciteDuration}
      SNEAK_INVIS_DURATION_MULTIPLIER: ${SNEAK_INVIS_DURATION_MULTIPLIER}
      ENABLE_COP_ZONE_CAP: ${ENABLE_COP_ZONE_CAP}
      NUMBER_OF_DM_EARRINGS: ${NUMBER_OF_DM_EARRINGS}
      HOMEPOINT_TELEPORT: ${HOMEPOINT_TELEPORT}
      ENM_COOLDOWN: ${ENM_COOLDOWN}
      FORCE_SPAWN_QM_RESET_TIME: ${FORCE_SPAWN_QM_RESET_TIME}
      VISITANT_BONUS: ${VISITANT_BONUS}
    volumes:
      - build-volume:/usr/build
  darkstar-dsconnect:
    container_name: darkstar-dsconnect
    build: 
      context: darkstar-dsconnect
      args:
        MYSQL_DATABASE: darkstar-db      
    depends_on:
      - darkstar-db
      - darkstar-dsbuild
    ports:
      - "54001:54001"
      - "54230:54230/tcp"
      - "54231:54231"
    volumes:
      - build-volume:/usr/build
    stdin_open: true
    tty: true
  darkstar-dsgame:
    container_name: darkstar-dsgame
    build: 
      context: darkstar-dsgame
      args:
        MYSQL_DATABASE: darkstar-db     
    depends_on:
      - darkstar-db
      - darkstar-dsbuild
      - darkstar-dsconnect
    ports:
      - "54230:54230/udp"
    volumes:
      - build-volume:/usr/build
  darkstar-dssearch:
    container_name: darkstar-dssearch
    build: 
      context: darkstar-dssearch
      args:
        MYSQL_DATABASE: darkstar-db      
    depends_on:
       - darkstar-db
       - darkstar-dsbuild
    ports:
       - "54002:54002"
    volumes:
       - build-volume:/usr/build
  darkstar-ahbroker:
    container_name: darkstar-ahbroker
    build:
      context: darkstar-ahbroker
      args:
        MYSQL_HOST: darkstar-db
        GITHUB_REPO: ${GITHUB_REPO_AHBROKER}
        GITHUB_BRANCH: ${GITHUB_BRANCH_AHBROKER}
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_LOGIN}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      AH_BOTNAME: ${ah_botname}
      AH_SINGLE: ${ah_single}
      AH_STACK: ${ah_stack}